//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class MSreplication_options
{
    public string optname { get; set; }
    public bool value { get; set; }
    public int major_version { get; set; }
    public int minor_version { get; set; }
    public int revision { get; set; }
    public int install_failures { get; set; }
}

public partial class spt_fallback_db
{
    public string xserver_name { get; set; }
    public System.DateTime xdttm_ins { get; set; }
    public System.DateTime xdttm_last_ins_upd { get; set; }
    public Nullable<short> xfallback_dbid { get; set; }
    public string name { get; set; }
    public short dbid { get; set; }
    public short status { get; set; }
    public short version { get; set; }
}

public partial class spt_fallback_dev
{
    public string xserver_name { get; set; }
    public System.DateTime xdttm_ins { get; set; }
    public System.DateTime xdttm_last_ins_upd { get; set; }
    public Nullable<int> xfallback_low { get; set; }
    public string xfallback_drive { get; set; }
    public int low { get; set; }
    public int high { get; set; }
    public short status { get; set; }
    public string name { get; set; }
    public string phyname { get; set; }
}

public partial class spt_fallback_usg
{
    public string xserver_name { get; set; }
    public System.DateTime xdttm_ins { get; set; }
    public System.DateTime xdttm_last_ins_upd { get; set; }
    public Nullable<int> xfallback_vstart { get; set; }
    public short dbid { get; set; }
    public int segmap { get; set; }
    public int lstart { get; set; }
    public int sizepg { get; set; }
    public int vstart { get; set; }
}

public partial class spt_monitor
{
    public System.DateTime lastrun { get; set; }
    public int cpu_busy { get; set; }
    public int io_busy { get; set; }
    public int idle { get; set; }
    public int pack_received { get; set; }
    public int pack_sent { get; set; }
    public int connections { get; set; }
    public int pack_errors { get; set; }
    public int total_read { get; set; }
    public int total_write { get; set; }
    public int total_errors { get; set; }
}

public partial class spt_values
{
    public string name { get; set; }
    public int number { get; set; }
    public string type { get; set; }
    public Nullable<int> low { get; set; }
    public Nullable<int> high { get; set; }
    public Nullable<int> status { get; set; }
}
