//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class masterEntities : DbContext
{
    public masterEntities()
        : base("name=masterEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
    public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
    public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
    public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
    public virtual DbSet<spt_monitor> spt_monitor { get; set; }
    public virtual DbSet<spt_values> spt_values { get; set; }

    public virtual int sp_MScleanupmergepublisher()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
    }

    public virtual int sp_MSrepl_startup()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
    }
}
